/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

/**
 *
 * @author Juanpi
 */
import java.text.SimpleDateFormat;
import java.util.List;
import logica.Ictrl;

import logica.Registro;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class PanelLaWebRegistro extends javax.swing.JPanel {

    /**
     * Creates new form PanelConsulta
     */
    Ictrl ic;

    private javax.swing.JPanel contenido;
    private java.awt.CardLayout c1;

    DefaultListModel modelo = new DefaultListModel();

    public PanelLaWebRegistro(Ictrl ic, javax.swing.JPanel contenido, java.awt.CardLayout c1) {
        initComponents();

        this.ic = ic;
        this.contenido = contenido;
        this.c1 = c1;

        listaRegistros.setModel(modelo);
        
        List<Registro> registros = ic.listarRegistros();
        registros.sort((r1, r2) -> r2.getFecha().compareTo(r1.getFecha()));
        // orden descendente (últimos primero)

        for (Registro r : registros) {
            String fila = String.format(
                    "%-15s | %-30s | %-10s | %-10s | %s",
                    r.getIp(),
                    r.getUrl(),
                    r.getBrowser(),
                    r.getSo(),
                    new SimpleDateFormat("dd/MM/yyyy HH:mm").format(r.getFecha())
            );
            modelo.addElement(fila);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaRegistros = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        labelImagen = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 240, 255));
        setMinimumSize(new java.awt.Dimension(1000, 900));
        setPreferredSize(new java.awt.Dimension(1000, 900));

        listaRegistros.setBackground(new java.awt.Color(255, 255, 255));
        listaRegistros.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        listaRegistros.setForeground(new java.awt.Color(16, 32, 56));
        listaRegistros.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaRegistrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaRegistros);

        jPanel1.setBackground(new java.awt.Color(255, 240, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(16, 32, 56));
        jLabel2.setText("Registro Acceso al Sitio Web");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel2)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(291, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listaRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaRegistrosMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_listaRegistrosMouseClicked

    private void recargarLista() {
        modelo.clear(); // limpia la lista visual
        for (Registro r : ic.listarRegistros()) {
            modelo.addElement(r.getIp());
        }
        listaRegistros.clearSelection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JList<String> listaRegistros;
    // End of variables declaration//GEN-END:variables
}
