
package clienteWS;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ictrlServicio", targetNamespace = "http://WebServices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IctrlServicio {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<clienteWS.ComentarioDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarComentariosDePropuesta", targetNamespace = "http://WebServices/", className = "clienteWS.ListarComentariosDePropuesta")
    @ResponseWrapper(localName = "listarComentariosDePropuestaResponse", targetNamespace = "http://WebServices/", className = "clienteWS.ListarComentariosDePropuestaResponse")
    @Action(input = "http://WebServices/ictrlServicio/listarComentariosDePropuestaRequest", output = "http://WebServices/ictrlServicio/listarComentariosDePropuestaResponse")
    public List<ComentarioDTO> listarComentariosDePropuesta(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<clienteWS.PropuestaDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarPropuestasNoIngresadas", targetNamespace = "http://WebServices/", className = "clienteWS.ListarPropuestasNoIngresadas")
    @ResponseWrapper(localName = "listarPropuestasNoIngresadasResponse", targetNamespace = "http://WebServices/", className = "clienteWS.ListarPropuestasNoIngresadasResponse")
    @Action(input = "http://WebServices/ictrlServicio/listarPropuestasNoIngresadasRequest", output = "http://WebServices/ictrlServicio/listarPropuestasNoIngresadasResponse")
    public List<PropuestaDTO> listarPropuestasNoIngresadas();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<clienteWS.PropuestaDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarPropuestasFinanciadas", targetNamespace = "http://WebServices/", className = "clienteWS.ListarPropuestasFinanciadas")
    @ResponseWrapper(localName = "listarPropuestasFinanciadasResponse", targetNamespace = "http://WebServices/", className = "clienteWS.ListarPropuestasFinanciadasResponse")
    @Action(input = "http://WebServices/ictrlServicio/listarPropuestasFinanciadasRequest", output = "http://WebServices/ictrlServicio/listarPropuestasFinanciadasResponse")
    public List<PropuestaDTO> listarPropuestasFinanciadas(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscoRol", targetNamespace = "http://WebServices/", className = "clienteWS.BuscoRol")
    @ResponseWrapper(localName = "buscoRolResponse", targetNamespace = "http://WebServices/", className = "clienteWS.BuscoRolResponse")
    @Action(input = "http://WebServices/ictrlServicio/buscoRolRequest", output = "http://WebServices/ictrlServicio/buscoRolResponse")
    public String buscoRol(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "usuarioSigueA", targetNamespace = "http://WebServices/", className = "clienteWS.UsuarioSigueA")
    @ResponseWrapper(localName = "usuarioSigueAResponse", targetNamespace = "http://WebServices/", className = "clienteWS.UsuarioSigueAResponse")
    @Action(input = "http://WebServices/ictrlServicio/usuarioSigueARequest", output = "http://WebServices/ictrlServicio/usuarioSigueAResponse")
    public boolean usuarioSigueA(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<clienteWS.UsuarioDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarSeguidores", targetNamespace = "http://WebServices/", className = "clienteWS.BuscarSeguidores")
    @ResponseWrapper(localName = "buscarSeguidoresResponse", targetNamespace = "http://WebServices/", className = "clienteWS.BuscarSeguidoresResponse")
    @Action(input = "http://WebServices/ictrlServicio/buscarSeguidoresRequest", output = "http://WebServices/ictrlServicio/buscarSeguidoresResponse")
    public List<UsuarioDTO> buscarSeguidores(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<clienteWS.UsuarioDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarSeguidos", targetNamespace = "http://WebServices/", className = "clienteWS.BuscarSeguidos")
    @ResponseWrapper(localName = "buscarSeguidosResponse", targetNamespace = "http://WebServices/", className = "clienteWS.BuscarSeguidosResponse")
    @Action(input = "http://WebServices/ictrlServicio/buscarSeguidosRequest", output = "http://WebServices/ictrlServicio/buscarSeguidosResponse")
    public List<UsuarioDTO> buscarSeguidos(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns clienteWS.Usuario
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscoUsuario", targetNamespace = "http://WebServices/", className = "clienteWS.BuscoUsuario")
    @ResponseWrapper(localName = "buscoUsuarioResponse", targetNamespace = "http://WebServices/", className = "clienteWS.BuscoUsuarioResponse")
    @Action(input = "http://WebServices/ictrlServicio/buscoUsuarioRequest", output = "http://WebServices/ictrlServicio/buscoUsuarioResponse")
    public Usuario buscoUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "cancelarPropuesta", targetNamespace = "http://WebServices/", className = "clienteWS.CancelarPropuesta")
    @ResponseWrapper(localName = "cancelarPropuestaResponse", targetNamespace = "http://WebServices/", className = "clienteWS.CancelarPropuestaResponse")
    @Action(input = "http://WebServices/ictrlServicio/cancelarPropuestaRequest", output = "http://WebServices/ictrlServicio/cancelarPropuestaResponse")
    public void cancelarPropuesta(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     */
    @WebMethod
    @RequestWrapper(localName = "altaColaboracion", targetNamespace = "http://WebServices/", className = "clienteWS.AltaColaboracion")
    @ResponseWrapper(localName = "altaColaboracionResponse", targetNamespace = "http://WebServices/", className = "clienteWS.AltaColaboracionResponse")
    @Action(input = "http://WebServices/ictrlServicio/altaColaboracionRequest", output = "http://WebServices/ictrlServicio/altaColaboracionResponse")
    public void altaColaboracion(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Float arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @RequestWrapper(localName = "dejarSeguir", targetNamespace = "http://WebServices/", className = "clienteWS.DejarSeguir")
    @ResponseWrapper(localName = "dejarSeguirResponse", targetNamespace = "http://WebServices/", className = "clienteWS.DejarSeguirResponse")
    @Action(input = "http://WebServices/ictrlServicio/dejarSeguirRequest", output = "http://WebServices/ictrlServicio/dejarSeguirResponse")
    public void dejarSeguir(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns clienteWS.Usuario
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscoUsuario2", targetNamespace = "http://WebServices/", className = "clienteWS.BuscoUsuario2")
    @ResponseWrapper(localName = "buscoUsuario2Response", targetNamespace = "http://WebServices/", className = "clienteWS.BuscoUsuario2Response")
    @Action(input = "http://WebServices/ictrlServicio/buscoUsuario2Request", output = "http://WebServices/ictrlServicio/buscoUsuario2Response")
    public Usuario buscoUsuario2(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     */
    @WebMethod
    @RequestWrapper(localName = "dejarComentario", targetNamespace = "http://WebServices/", className = "clienteWS.DejarComentario")
    @ResponseWrapper(localName = "dejarComentarioResponse", targetNamespace = "http://WebServices/", className = "clienteWS.DejarComentarioResponse")
    @Action(input = "http://WebServices/ictrlServicio/dejarComentarioRequest", output = "http://WebServices/ictrlServicio/dejarComentarioResponse")
    public void dejarComentario(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validarUsuario", targetNamespace = "http://WebServices/", className = "clienteWS.ValidarUsuario")
    @ResponseWrapper(localName = "validarUsuarioResponse", targetNamespace = "http://WebServices/", className = "clienteWS.ValidarUsuarioResponse")
    @Action(input = "http://WebServices/ictrlServicio/validarUsuarioRequest", output = "http://WebServices/ictrlServicio/validarUsuarioResponse")
    public boolean validarUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns clienteWS.PropuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscoPropuestaDTO", targetNamespace = "http://WebServices/", className = "clienteWS.BuscoPropuestaDTO")
    @ResponseWrapper(localName = "buscoPropuestaDTOResponse", targetNamespace = "http://WebServices/", className = "clienteWS.BuscoPropuestaDTOResponse")
    @Action(input = "http://WebServices/ictrlServicio/buscoPropuestaDTORequest", output = "http://WebServices/ictrlServicio/buscoPropuestaDTOResponse")
    public PropuestaDTO buscoPropuestaDTO(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     */
    @WebMethod
    @RequestWrapper(localName = "registrarAcceso", targetNamespace = "http://WebServices/", className = "clienteWS.RegistrarAcceso")
    @ResponseWrapper(localName = "registrarAccesoResponse", targetNamespace = "http://WebServices/", className = "clienteWS.RegistrarAccesoResponse")
    @Action(input = "http://WebServices/ictrlServicio/registrarAccesoRequest", output = "http://WebServices/ictrlServicio/registrarAccesoResponse")
    public void registrarAcceso(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @return
     *     returns java.util.List<clienteWS.Proponente>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarProponentes", targetNamespace = "http://WebServices/", className = "clienteWS.ListarProponentes")
    @ResponseWrapper(localName = "listarProponentesResponse", targetNamespace = "http://WebServices/", className = "clienteWS.ListarProponentesResponse")
    @Action(input = "http://WebServices/ictrlServicio/listarProponentesRequest", output = "http://WebServices/ictrlServicio/listarProponentesResponse")
    public List<Proponente> listarProponentes();

    /**
     * 
     * @return
     *     returns java.util.List<clienteWS.Categoria>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarCategoria", targetNamespace = "http://WebServices/", className = "clienteWS.ListarCategoria")
    @ResponseWrapper(localName = "listarCategoriaResponse", targetNamespace = "http://WebServices/", className = "clienteWS.ListarCategoriaResponse")
    @Action(input = "http://WebServices/ictrlServicio/listarCategoriaRequest", output = "http://WebServices/ictrlServicio/listarCategoriaResponse")
    public List<Categoria> listarCategoria();

    /**
     * 
     * @return
     *     returns java.util.List<clienteWS.Propuesta>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarPropuestas", targetNamespace = "http://WebServices/", className = "clienteWS.ListarPropuestas")
    @ResponseWrapper(localName = "listarPropuestasResponse", targetNamespace = "http://WebServices/", className = "clienteWS.ListarPropuestasResponse")
    @Action(input = "http://WebServices/ictrlServicio/listarPropuestasRequest", output = "http://WebServices/ictrlServicio/listarPropuestasResponse")
    public List<Propuesta> listarPropuestas();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "modificoPropuesta", targetNamespace = "http://WebServices/", className = "clienteWS.ModificoPropuesta")
    @ResponseWrapper(localName = "modificoPropuestaResponse", targetNamespace = "http://WebServices/", className = "clienteWS.ModificoPropuestaResponse")
    @Action(input = "http://WebServices/ictrlServicio/modificoPropuestaRequest", output = "http://WebServices/ictrlServicio/modificoPropuestaResponse")
    public void modificoPropuesta(
        @WebParam(name = "arg0", targetNamespace = "")
        Propuesta arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg10
     * @param arg11
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     */
    @WebMethod
    @RequestWrapper(localName = "altaPropuesta", targetNamespace = "http://WebServices/", className = "clienteWS.AltaPropuesta")
    @ResponseWrapper(localName = "altaPropuestaResponse", targetNamespace = "http://WebServices/", className = "clienteWS.AltaPropuestaResponse")
    @Action(input = "http://WebServices/ictrlServicio/altaPropuestaRequest", output = "http://WebServices/ictrlServicio/altaPropuestaResponse")
    public void altaPropuesta(
        @WebParam(name = "arg0", targetNamespace = "")
        Proponente arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        float arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        float arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        byte[] arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        String arg11);

    /**
     * 
     * @param arg0
     * @return
     *     returns clienteWS.Propuesta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscoPropuesta", targetNamespace = "http://WebServices/", className = "clienteWS.BuscoPropuesta")
    @ResponseWrapper(localName = "buscoPropuestaResponse", targetNamespace = "http://WebServices/", className = "clienteWS.BuscoPropuestaResponse")
    @Action(input = "http://WebServices/ictrlServicio/buscoPropuestaRequest", output = "http://WebServices/ictrlServicio/buscoPropuestaResponse")
    public Propuesta buscoPropuesta(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @RequestWrapper(localName = "seguirUsuario", targetNamespace = "http://WebServices/", className = "clienteWS.SeguirUsuario")
    @ResponseWrapper(localName = "seguirUsuarioResponse", targetNamespace = "http://WebServices/", className = "clienteWS.SeguirUsuarioResponse")
    @Action(input = "http://WebServices/ictrlServicio/seguirUsuarioRequest", output = "http://WebServices/ictrlServicio/seguirUsuarioResponse")
    public void seguirUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns clienteWS.Colaborador
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscoColaborador", targetNamespace = "http://WebServices/", className = "clienteWS.BuscoColaborador")
    @ResponseWrapper(localName = "buscoColaboradorResponse", targetNamespace = "http://WebServices/", className = "clienteWS.BuscoColaboradorResponse")
    @Action(input = "http://WebServices/ictrlServicio/buscoColaboradorRequest", output = "http://WebServices/ictrlServicio/buscoColaboradorResponse")
    public Colaborador buscoColaborador(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns clienteWS.Proponente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscoProponente", targetNamespace = "http://WebServices/", className = "clienteWS.BuscoProponente")
    @ResponseWrapper(localName = "buscoProponenteResponse", targetNamespace = "http://WebServices/", className = "clienteWS.BuscoProponenteResponse")
    @Action(input = "http://WebServices/ictrlServicio/buscoProponenteRequest", output = "http://WebServices/ictrlServicio/buscoProponenteResponse")
    public Proponente buscoProponente(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<clienteWS.Colaborador>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarColaboradores", targetNamespace = "http://WebServices/", className = "clienteWS.ListarColaboradores")
    @ResponseWrapper(localName = "listarColaboradoresResponse", targetNamespace = "http://WebServices/", className = "clienteWS.ListarColaboradoresResponse")
    @Action(input = "http://WebServices/ictrlServicio/listarColaboradoresRequest", output = "http://WebServices/ictrlServicio/listarColaboradoresResponse")
    public List<Colaborador> listarColaboradores();

    /**
     * 
     * @return
     *     returns java.util.List<clienteWS.Colaboracion>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarColaboraciones", targetNamespace = "http://WebServices/", className = "clienteWS.ListarColaboraciones")
    @ResponseWrapper(localName = "listarColaboracionesResponse", targetNamespace = "http://WebServices/", className = "clienteWS.ListarColaboracionesResponse")
    @Action(input = "http://WebServices/ictrlServicio/listarColaboracionesRequest", output = "http://WebServices/ictrlServicio/listarColaboracionesResponse")
    public List<Colaboracion> listarColaboraciones();

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @param arg8
     */
    @WebMethod
    @RequestWrapper(localName = "altaPerfilProponente", targetNamespace = "http://WebServices/", className = "clienteWS.AltaPerfilProponente")
    @ResponseWrapper(localName = "altaPerfilProponenteResponse", targetNamespace = "http://WebServices/", className = "clienteWS.AltaPerfilProponenteResponse")
    @Action(input = "http://WebServices/ictrlServicio/altaPerfilProponenteRequest", output = "http://WebServices/ictrlServicio/altaPerfilProponenteResponse")
    public void altaPerfilProponente(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        byte[] arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8);

    /**
     * 
     * @return
     *     returns java.util.List<clienteWS.PropuestaDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarPropuestasDTO", targetNamespace = "http://WebServices/", className = "clienteWS.ListarPropuestasDTO")
    @ResponseWrapper(localName = "listarPropuestasDTOResponse", targetNamespace = "http://WebServices/", className = "clienteWS.ListarPropuestasDTOResponse")
    @Action(input = "http://WebServices/ictrlServicio/listarPropuestasDTORequest", output = "http://WebServices/ictrlServicio/listarPropuestasDTOResponse")
    public List<PropuestaDTO> listarPropuestasDTO();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<clienteWS.PropuestaDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarPropuestasPublicadas", targetNamespace = "http://WebServices/", className = "clienteWS.ListarPropuestasPublicadas")
    @ResponseWrapper(localName = "listarPropuestasPublicadasResponse", targetNamespace = "http://WebServices/", className = "clienteWS.ListarPropuestasPublicadasResponse")
    @Action(input = "http://WebServices/ictrlServicio/listarPropuestasPublicadasRequest", output = "http://WebServices/ictrlServicio/listarPropuestasPublicadasResponse")
    public List<PropuestaDTO> listarPropuestasPublicadas(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @RequestWrapper(localName = "cambiarEstadoPropuesta", targetNamespace = "http://WebServices/", className = "clienteWS.CambiarEstadoPropuesta")
    @ResponseWrapper(localName = "cambiarEstadoPropuestaResponse", targetNamespace = "http://WebServices/", className = "clienteWS.CambiarEstadoPropuestaResponse")
    @Action(input = "http://WebServices/ictrlServicio/cambiarEstadoPropuestaRequest", output = "http://WebServices/ictrlServicio/cambiarEstadoPropuestaResponse")
    public void cambiarEstadoPropuesta(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.util.List<clienteWS.ProponenteDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarProponentesDTO", targetNamespace = "http://WebServices/", className = "clienteWS.ListarProponentesDTO")
    @ResponseWrapper(localName = "listarProponentesDTOResponse", targetNamespace = "http://WebServices/", className = "clienteWS.ListarProponentesDTOResponse")
    @Action(input = "http://WebServices/ictrlServicio/listarProponentesDTORequest", output = "http://WebServices/ictrlServicio/listarProponentesDTOResponse")
    public List<ProponenteDTO> listarProponentesDTO();

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     */
    @WebMethod
    @RequestWrapper(localName = "altaPerfilColaborador", targetNamespace = "http://WebServices/", className = "clienteWS.AltaPerfilColaborador")
    @ResponseWrapper(localName = "altaPerfilColaboradorResponse", targetNamespace = "http://WebServices/", className = "clienteWS.AltaPerfilColaboradorResponse")
    @Action(input = "http://WebServices/ictrlServicio/altaPerfilColaboradorRequest", output = "http://WebServices/ictrlServicio/altaPerfilColaboradorResponse")
    public void altaPerfilColaborador(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        byte[] arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

    /**
     * 
     * @return
     *     returns java.util.List<clienteWS.ColaboradorDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarColaboradoresDTO", targetNamespace = "http://WebServices/", className = "clienteWS.ListarColaboradoresDTO")
    @ResponseWrapper(localName = "listarColaboradoresDTOResponse", targetNamespace = "http://WebServices/", className = "clienteWS.ListarColaboradoresDTOResponse")
    @Action(input = "http://WebServices/ictrlServicio/listarColaboradoresDTORequest", output = "http://WebServices/ictrlServicio/listarColaboradoresDTOResponse")
    public List<ColaboradorDTO> listarColaboradoresDTO();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<clienteWS.PropuestaDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarPropuestasIngresadas", targetNamespace = "http://WebServices/", className = "clienteWS.ListarPropuestasIngresadas")
    @ResponseWrapper(localName = "listarPropuestasIngresadasResponse", targetNamespace = "http://WebServices/", className = "clienteWS.ListarPropuestasIngresadasResponse")
    @Action(input = "http://WebServices/ictrlServicio/listarPropuestasIngresadasRequest", output = "http://WebServices/ictrlServicio/listarPropuestasIngresadasResponse")
    public List<PropuestaDTO> listarPropuestasIngresadas(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<clienteWS.PropuestaDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarPropuestasFavoritas", targetNamespace = "http://WebServices/", className = "clienteWS.ListarPropuestasFavoritas")
    @ResponseWrapper(localName = "listarPropuestasFavoritasResponse", targetNamespace = "http://WebServices/", className = "clienteWS.ListarPropuestasFavoritasResponse")
    @Action(input = "http://WebServices/ictrlServicio/listarPropuestasFavoritasRequest", output = "http://WebServices/ictrlServicio/listarPropuestasFavoritasResponse")
    public List<PropuestaDTO> listarPropuestasFavoritas(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param nombre
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saludar", targetNamespace = "http://WebServices/", className = "clienteWS.Saludar")
    @ResponseWrapper(localName = "saludarResponse", targetNamespace = "http://WebServices/", className = "clienteWS.SaludarResponse")
    @Action(input = "http://WebServices/ictrlServicio/saludarRequest", output = "http://WebServices/ictrlServicio/saludarResponse")
    public String saludar(
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre);

    /**
     * 
     * @param arg0
     * @return
     *     returns clienteWS.ColaboradorDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscoColaboradorDTO", targetNamespace = "http://WebServices/", className = "clienteWS.BuscoColaboradorDTO")
    @ResponseWrapper(localName = "buscoColaboradorDTOResponse", targetNamespace = "http://WebServices/", className = "clienteWS.BuscoColaboradorDTOResponse")
    @Action(input = "http://WebServices/ictrlServicio/buscoColaboradorDTORequest", output = "http://WebServices/ictrlServicio/buscoColaboradorDTOResponse")
    public ColaboradorDTO buscoColaboradorDTO(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<clienteWS.ColaboracionDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarColaboracionesDTO", targetNamespace = "http://WebServices/", className = "clienteWS.ListarColaboracionesDTO")
    @ResponseWrapper(localName = "listarColaboracionesDTOResponse", targetNamespace = "http://WebServices/", className = "clienteWS.ListarColaboracionesDTOResponse")
    @Action(input = "http://WebServices/ictrlServicio/listarColaboracionesDTORequest", output = "http://WebServices/ictrlServicio/listarColaboracionesDTOResponse")
    public List<ColaboracionDTO> listarColaboracionesDTO();

    /**
     * 
     * @param arg0
     * @return
     *     returns clienteWS.UsuarioDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscoUsuarioDTO", targetNamespace = "http://WebServices/", className = "clienteWS.BuscoUsuarioDTO")
    @ResponseWrapper(localName = "buscoUsuarioDTOResponse", targetNamespace = "http://WebServices/", className = "clienteWS.BuscoUsuarioDTOResponse")
    @Action(input = "http://WebServices/ictrlServicio/buscoUsuarioDTORequest", output = "http://WebServices/ictrlServicio/buscoUsuarioDTOResponse")
    public UsuarioDTO buscoUsuarioDTO(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<clienteWS.CategoriaDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarCategoriaDTO", targetNamespace = "http://WebServices/", className = "clienteWS.ListarCategoriaDTO")
    @ResponseWrapper(localName = "listarCategoriaDTOResponse", targetNamespace = "http://WebServices/", className = "clienteWS.ListarCategoriaDTOResponse")
    @Action(input = "http://WebServices/ictrlServicio/listarCategoriaDTORequest", output = "http://WebServices/ictrlServicio/listarCategoriaDTOResponse")
    public List<CategoriaDTO> listarCategoriaDTO();

}
