
package clienteWS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ictrlServicioService", targetNamespace = "http://WebServices/", wsdlLocation = "http://localhost:8085/servicio?wsdl")
public class IctrlServicioService
    extends Service
{

    private static final URL ICTRLSERVICIOSERVICE_WSDL_LOCATION;
    private static final WebServiceException ICTRLSERVICIOSERVICE_EXCEPTION;
    private static final QName ICTRLSERVICIOSERVICE_QNAME = new QName("http://WebServices/", "ictrlServicioService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/servicio?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ICTRLSERVICIOSERVICE_WSDL_LOCATION = url;
        ICTRLSERVICIOSERVICE_EXCEPTION = e;
    }

    public IctrlServicioService() {
        super(__getWsdlLocation(), ICTRLSERVICIOSERVICE_QNAME);
    }

    public IctrlServicioService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ICTRLSERVICIOSERVICE_QNAME, features);
    }

    public IctrlServicioService(URL wsdlLocation) {
        super(wsdlLocation, ICTRLSERVICIOSERVICE_QNAME);
    }

    public IctrlServicioService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ICTRLSERVICIOSERVICE_QNAME, features);
    }

    public IctrlServicioService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IctrlServicioService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IctrlServicio
     */
    @WebEndpoint(name = "ictrlServicioPort")
    public IctrlServicio getIctrlServicioPort() {
        return super.getPort(new QName("http://WebServices/", "ictrlServicioPort"), IctrlServicio.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IctrlServicio
     */
    @WebEndpoint(name = "ictrlServicioPort")
    public IctrlServicio getIctrlServicioPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebServices/", "ictrlServicioPort"), IctrlServicio.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ICTRLSERVICIOSERVICE_EXCEPTION!= null) {
            throw ICTRLSERVICIOSERVICE_EXCEPTION;
        }
        return ICTRLSERVICIOSERVICE_WSDL_LOCATION;
    }

}
