/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2025-10-23 08:15:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import logica.*;
import java.util.List;
import javax.servlet.http.HttpSession;

public final class altaPropuesta_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("logica");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    HttpSession sesion = request.getSession(false);
    String rol = null;
    String usuario = null;

    if (sesion != null) {
        rol = (String) sesion.getAttribute("rol");
        usuario = (String) sesion.getAttribute("usuarioLogueado");
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Alta de propuesta</title>\n");
      out.write("        <style>\n");
      out.write("            body {\n");
      out.write("                font-family: Arial, sans-serif;\n");
      out.write("                margin:0;\n");
      out.write("                background:#f5f7fa;\n");
      out.write("            }\n");
      out.write("            header {\n");
      out.write("                background:#2c3e50;\n");
      out.write("                color:white;\n");
      out.write("                padding:15px 25px;\n");
      out.write("                display:flex;\n");
      out.write("                justify-content:space-between;\n");
      out.write("                align-items:center;\n");
      out.write("            }\n");
      out.write("            header h1 {\n");
      out.write("                margin:0;\n");
      out.write("                font-size:20px;\n");
      out.write("            }\n");
      out.write("            nav a {\n");
      out.write("                color:white;\n");
      out.write("                margin:0 10px;\n");
      out.write("                text-decoration:none;\n");
      out.write("            }\n");
      out.write("            nav a:hover {\n");
      out.write("                text-decoration:underline;\n");
      out.write("            }\n");
      out.write("            .container {\n");
      out.write("                padding:30px;\n");
      out.write("            }\n");
      out.write("            .card {\n");
      out.write("                background:white;\n");
      out.write("                border-radius:8px;\n");
      out.write("                box-shadow:0 2px 6px rgba(0,0,0,0.1);\n");
      out.write("                padding:25px;\n");
      out.write("                max-width:600px;\n");
      out.write("                margin:0 auto;\n");
      out.write("            }\n");
      out.write("            h2 {\n");
      out.write("                color:#2c3e50;\n");
      out.write("                margin-bottom:15px;\n");
      out.write("            }\n");
      out.write("            p {\n");
      out.write("                margin:8px 0;\n");
      out.write("            }\n");
      out.write("            .actions {\n");
      out.write("                margin-top:20px;\n");
      out.write("            }\n");
      out.write("            .actions a {\n");
      out.write("                display:inline-block;\n");
      out.write("                padding:10px 20px;\n");
      out.write("                background:#3498db;\n");
      out.write("                color:white;\n");
      out.write("                border-radius:5px;\n");
      out.write("                text-decoration:none;\n");
      out.write("                margin-right:10px;\n");
      out.write("            }\n");
      out.write("            .actions a:hover {\n");
      out.write("                background:#2980b9;\n");
      out.write("            }\n");
      out.write("    </style>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <header>\n");
      out.write("            <h1>🌐 Culturarte</h1>\n");
      out.write("            <nav>\n");
      out.write("                <a href=\"index.jsp\">🏠 Inicio</a>\n");
      out.write("\n");
      out.write("                ");
 if (usuario != null && !"visitante".equalsIgnoreCase(rol)) {
      out.write("\n");
      out.write("                <span style=\"margin-right:10px;\">👤 ");
      out.print( usuario);
      out.write("</span>\n");
      out.write("                <a href=\"logout\">🚪 Cerrar Sesión</a>\n");
      out.write("                ");
 } else { 
      out.write("\n");
      out.write("                <a href=\"altaPerfil.jsp\">🆕 Crear Cuenta</a>\n");
      out.write("                <a href=\"inicioSesion.jsp\">🔑 Iniciar Sesión</a>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            </nav>\n");
      out.write("        </header> \n");
      out.write("        <div class=\"container\">\n");
      out.write("    <div class=\"card\">\n");
      out.write("        <h2>🆕 Alta de Propuesta</h2>\n");
      out.write("        <form action=\"altaPropuestaServlet\" method=\"POST\">\n");
      out.write("\n");
      out.write("            <input type=\"text\" name=\"titulo\" placeholder=\"Titulo\" required>\n");
      out.write("\n");
      out.write("            <input type=\"text\" name=\"descripcion\" placeholder=\"Descripcion\" required>\n");
      out.write("\n");
      out.write("            <select name=\"tipoEspectaculo\" id=\"tipoEspectaculo\" required>\n");
      out.write("                <option value=\"\">-- Seleccione un tipo --</option>\n");
      out.write("                ");

                    List<categoria> tipos = (List<categoria>) request.getAttribute("tiposCategorias");
                    if (tipos != null) {
                        for (categoria c : tipos) {
                
      out.write("\n");
      out.write("                <option value=\"");
      out.print( c.getNombre());
      out.write('"');
      out.write('>');
      out.print( c.getNombre());
      out.write("</option>\n");
      out.write("                ");

                        }
                    }
                
      out.write("\n");
      out.write("            </select>\n");
      out.write("\n");
      out.write("            <input type=\"text\" name=\"lugar\" placeholder=\"Lugar\" required>\n");
      out.write("            \n");
      out.write("            <input type=\"date\" name=\"fechaRealizacion\" placeholder=\"Fecha Realizacion\" required>\n");
      out.write("            <input type=\"time\" id=\"horaRealizacion\" name=\"horaRealizacion\" required>\n");
      out.write("            \n");
      out.write("            <input type=\"number\" name=\"precioEntrada\" placeholder=\"Precio entrada\" required>\n");
      out.write("            <input type=\"number\" name=\"montoNecesario\" placeholder=\"Monto necesario\" required>\n");
      out.write("\n");
      out.write("            <select name=\"tipoRetorno\" id=\"tipoRetorno\" required>\n");
      out.write("                <option value=\"\">-- Seleccione un tipo --</option>\n");
      out.write("                <option value=\"Entrada\">Entrada</option>\n");
      out.write("                <option value=\"Porcentaj\">Porcentaje</option>\n");
      out.write("                <option value=\"Ambos\">Ambos</option>\n");
      out.write("            </select>\n");
      out.write("\n");
      out.write("                <button type=\"submit\">✅ Crear Propuesta</button>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
