/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2025-11-08 19:04:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.http.HttpSession;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    HttpSession sesion = request.getSession(false);
    String rol = null;
    String usuario = null;

    if (sesion != null) {
        rol = (String) sesion.getAttribute("rol");
        usuario = (String) sesion.getAttribute("usuarioLogueado");
    }else {
        // si no hay sesion, simulamos visitante
        rol = "visitante";
        usuario = "visitante";
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <title>Culturarte - Principal</title>\r\n");
      out.write("\r\n");
      out.write("        <style>\r\n");
      out.write("            body {\r\n");
      out.write("                margin: 0;\r\n");
      out.write("                font-family: 'Segoe UI', Arial, sans-serif;\r\n");
      out.write("                background: #f5f7fa;\r\n");
      out.write("                color: #2c3e50;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            header {\r\n");
      out.write("                background: #ffffff;\r\n");
      out.write("                border-bottom: 1px solid #ddd;\r\n");
      out.write("                padding: 15px 40px;\r\n");
      out.write("                display: flex;\r\n");
      out.write("                justify-content: space-between;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                position: sticky;\r\n");
      out.write("                top: 0;\r\n");
      out.write("                z-index: 10;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            header h1 {\r\n");
      out.write("                margin: 0;\r\n");
      out.write("                font-size: 22px;\r\n");
      out.write("                color: #2c3e50;\r\n");
      out.write("                font-weight: bold;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            nav a {\r\n");
      out.write("                color: #2c3e50;\r\n");
      out.write("                text-decoration: none;\r\n");
      out.write("                font-weight: 500;\r\n");
      out.write("                margin: 0 10px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            nav a:hover {\r\n");
      out.write("                color: #3498db;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .buscador {\r\n");
      out.write("                background: #ecf0f1;\r\n");
      out.write("                padding: 20px;\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                display: flex;\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("                gap: 10px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .buscador input {\r\n");
      out.write("                flex: 1;\r\n");
      out.write("                max-width: 600px;\r\n");
      out.write("                padding: 10px;\r\n");
      out.write("                border: 1px solid #ccc;\r\n");
      out.write("                border-radius: 6px;\r\n");
      out.write("                font-size: 15px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .buscador button {\r\n");
      out.write("                background: #3498db;\r\n");
      out.write("                color: white;\r\n");
      out.write("                border: none;\r\n");
      out.write("                border-radius: 6px;\r\n");
      out.write("                padding: 10px 20px;\r\n");
      out.write("                font-weight: bold;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("                transition: background 0.3s;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .buscador button:hover {\r\n");
      out.write("                background: #2980b9;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .content {\r\n");
      out.write("                max-width: 1100px;\r\n");
      out.write("                margin: 40px auto;\r\n");
      out.write("                padding: 0 20px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            h2 {\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                color: #2c3e50;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .tarjetas {\r\n");
      out.write("                display: flex;\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("                flex-wrap: wrap;\r\n");
      out.write("                gap: 25px;\r\n");
      out.write("                margin-top: 40px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .card {\r\n");
      out.write("                background: #fff;\r\n");
      out.write("                border-radius: 12px;\r\n");
      out.write("                box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("                padding: 25px;\r\n");
      out.write("                width: 300px;\r\n");
      out.write("                transition: transform 0.2s ease;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .card:hover {\r\n");
      out.write("                transform: translateY(-5px);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .card h3 {\r\n");
      out.write("                color: #3498db;\r\n");
      out.write("                margin-bottom: 10px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .card p {\r\n");
      out.write("                color: #555;\r\n");
      out.write("                font-size: 14px;\r\n");
      out.write("                margin-bottom: 15px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .card a {\r\n");
      out.write("                display: inline-block;\r\n");
      out.write("                background: #3498db;\r\n");
      out.write("                color: white;\r\n");
      out.write("                padding: 8px 15px;\r\n");
      out.write("                border-radius: 6px;\r\n");
      out.write("                text-decoration: none;\r\n");
      out.write("                font-weight: bold;\r\n");
      out.write("                font-size: 14px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .card a:hover {\r\n");
      out.write("                background: #2980b9;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            footer {\r\n");
      out.write("                background: #2c3e50;\r\n");
      out.write("                color: white;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                padding: 15px 0;\r\n");
      out.write("                margin-top: 60px;\r\n");
      out.write("                font-size: 14px;\r\n");
      out.write("            }\r\n");
      out.write("        </style>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("\r\n");
      out.write("       <header>\r\n");
      out.write("            <h1>🌐 Culturarte</h1>\r\n");
      out.write("            <nav>\r\n");
      out.write("                <a href=\"index.jsp\">🏠 Inicio</a>\r\n");
      out.write("\r\n");
      out.write("                ");
 if (usuario != null && !"visitante".equalsIgnoreCase(rol)) {
      out.write("\r\n");
      out.write("                <span style=\"margin-right:10px;\">👤 ");
      out.print( usuario);
      out.write("</span>\r\n");
      out.write("                <a href=\"logout\">🚪 Cerrar Sesión</a>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                <a href=\"altaPerfil.jsp\">🆕 Crear Cuenta</a>\r\n");
      out.write("                <a href=\"inicioSesion.jsp\">🔑 Iniciar Sesión</a>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </nav>\r\n");
      out.write("        </header> \r\n");
      out.write("\r\n");
      out.write("        <div class=\"buscador\">\r\n");
      out.write("            <form action=\"consultaPropuestaServlet\" method=\"GET\" style=\"display:flex; width:70%; gap:10px;\">\r\n");
      out.write("                <input type=\"text\" name=\"filtros\" placeholder=\"Buscar por título, descripción o lugar (separá por comas)\">\r\n");
      out.write("                <button type=\"submit\">🔍 Buscar</button>\r\n");
      out.write("            </form>\r\n");
      out.write("            ");
 if (usuario != null && !"visitante".equalsIgnoreCase(rol)) {
      out.write("\r\n");
      out.write("            <form action=\"consultaPerfilServlet\" method=\"GET\" \r\n");
      out.write("                  style=\"display:flex; align-items:center; gap:5px;\">\r\n");
      out.write("                <input type=\"text\" name=\"nickname\" placeholder=\"Buscar usuario...\"\r\n");
      out.write("                       style=\"padding:6px 8px; border:1px solid #ccc; border-radius:5px; font-size:13px; width:130px;\">\r\n");
      out.write("                <button type=\"submit\" \r\n");
      out.write("                        style=\"background:#3498db; border:none; color:white; border-radius:5px; padding:6px 10px; cursor:pointer;\">\r\n");
      out.write("                    🔍\r\n");
      out.write("                </button>\r\n");
      out.write("            </form>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"content\">\r\n");
      out.write("            ");
 if (rol == null || "visitante".equalsIgnoreCase(rol)) { 
      out.write("\r\n");
      out.write("            <h2>Bienvenido Visitante 🤝</h2>\r\n");
      out.write("            <p style=\"text-align:center; color:#555;\">Explorá las propuestas, Conoce nuestros usuarios o iniciá sesión para acceder a más funciones.</p>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"tarjetas\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <h3>📚 Ver Propuestas</h3>\r\n");
      out.write("                    <p>Explorá los proyectos culturales disponibles.</p>\r\n");
      out.write("                    <a href=\"consultaPropuestaServlet\">Ver</a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <h3>👥 Usuarios</h3>\r\n");
      out.write("                    <p>Descubrí quiénes forman parte de nuestra comunidad.</p>\r\n");
      out.write("                    <a href=\"consultaUsuariosServlet\">Ver</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            ");
 } else if ("proponente".equalsIgnoreCase(rol)) {
      out.write("\r\n");
      out.write("            <h2>Bienvenido, ");
      out.print( usuario);
      out.write(" 🎭</h2>\r\n");
      out.write("            <p style=\"text-align:center; color:#555;\">Gestioná tus propuestas y conectá con tus colaboradores.</p>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"tarjetas\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <h3>➕ Crear Propuesta</h3>\r\n");
      out.write("                    <p>Publicá tu nuevo espectáculo o evento cultural.</p>\r\n");
      out.write("                    <a href=\"altaPropuestaServlet\">Ir</a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <h3>💰 Extender Financiación</h3>\r\n");
      out.write("                    <p>Amplía el período de financiación de tus proyectos.</p>\r\n");
      out.write("                    <a href=\"extenderFinanciacion.jsp\">Ir</a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <h3>🛑 Cancelar Propuesta</h3>\r\n");
      out.write("                    <p>Gestioná las propuestas que ya no quieras mantener activas.</p>\r\n");
      out.write("                    <a href=\"cancelarPropuestaServlet\">Ir</a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <h3>📂 Ver Propuestas</h3>\r\n");
      out.write("                    <p>Consultá todas tus propuestas activas y su estado.</p>\r\n");
      out.write("                    <a href=\"consultaPropuestaServlet\">Ver</a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <h3>📂 Mis propuestas favoritas</h3>\r\n");
      out.write("                    <p>Administra las Propuestas que mas te llamen la atencion.</p>\r\n");
      out.write("                    <a href=\"propuestaFavoritaServlet\">Ver</a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <h3>👥 Nuestros Usuarios</h3>\r\n");
      out.write("                    <p>Descubrí quiénes forman parte de nuestra comunidad.</p>\r\n");
      out.write("                    <a href=\"consultaUsuariosServlet\">Ver</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            ");
 } else if ("colaborador".equalsIgnoreCase(rol)) {
      out.write("\r\n");
      out.write("            <h2>Bienvenido, ");
      out.print( usuario);
      out.write(" 🤝</h2>\r\n");
      out.write("            <p style=\"text-align:center; color:#555;\">Explorá proyectos culturales y colaborá en tus favoritos.</p>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"tarjetas\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <h3>💸 Colaborar</h3>\r\n");
      out.write("                    <p>Apoyá propuestas culturales con tus aportes.</p>\r\n");
      out.write("                    <a href=\"altaColaboracionServlet\">Ir</a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <h3>💬 Comentarios</h3>\r\n");
      out.write("                    <p>Compartí tu opinión y experiencias con las propuestas.</p>\r\n");
      out.write("                    <a href=\"AgregarComentario.jsp\">Ir</a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <h3>📚 Ver Propuestas</h3>\r\n");
      out.write("                    <p>Explorá todas las propuestas disponibles.</p>\r\n");
      out.write("                    <a href=\"consultaPropuestaServlet\">Ver</a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <h3>📂 Mis propuestas favoritas</h3>\r\n");
      out.write("                    <p>Administra las Propuestas que mas te llamen la atencion.</p>\r\n");
      out.write("                    <a href=\"propuestaFavoritaServlet\">Ver</a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <h3>👥 Nuestros Usuarios</h3>\r\n");
      out.write("                    <p>Descubrí quiénes forman parte de nuestra comunidad.</p>\r\n");
      out.write("                    <a href=\"consultaUsuariosServlet\">Ver</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            ");
 } else if ("admin".equalsIgnoreCase(rol)) {
      out.write("\r\n");
      out.write("            <h2>Bienvenido Administrador, ");
      out.print( usuario);
      out.write(" 🛠️</h2>\r\n");
      out.write("            <p style=\"text-align:center; color:#555;\">Supervisá y evaluá las propuestas de la plataforma.</p>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"tarjetas\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <h3>🌍 Evaluar Propuestas</h3>\r\n");
      out.write("                    <p>Accedé al panel de revisión y control de proyectos.</p>\r\n");
      out.write("                    <a href=\"adminServlet\">Ir</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 }
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <footer>\r\n");
      out.write("            © 2025 Culturarte - Plataforma Cultural\r\n");
      out.write("        </footer>\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
